config/routes.rb
MotionWeb::Application.routes.draw do
  resources :records

  resources :camcorders

  controller :sessions do
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    delete 'logout' => :destroy
    get 'logout', to: 'sessions#destroy', as: 'logout', :via => :delete
    #post 'logout', to: 'sessions#destroy', as: 'logout', :via => :delete
  end

  resources :users

  resources :sessions

  get "home/index"
  get "home/live"
  get "home/view"
  root :to => 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == "admin"
        can :manage, :all
    elsif user.role == "moderator"
        can :manage, Camcorder
        can :manage, Record
        can :read, :all
    elsif user.role == "viewer"
        can :read, :root
        can :read, Camcorder
        can :read, Record
    else
        can :read, :root
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/camcorder.rb
class Camcorder < ActiveRecord::Base
  attr_accessible :description, :name, :thread, :stream_port
  validates_uniqueness_of :thread, :name, :stream_port
  validates_presence_of :thread, :name, :stream_port

  has_many :Records, :dependent => :destroy, :foreign_key => 'thread'
end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :event_timestamp, :file_type, :filename, :frame, :thread

  belongs_to :camcorder, :foreign_key => 'thread'

  self.per_page = 15

  def self.get_video_files
  	where("file_type = 8").order(:id)
  end

  def self.clean_old_records (days = 21)
  	clean_sql = "DELETE FROM records WHERE event_timestamp < TIMESTAMP 'NOW()' - INTERVAL '#{days} days'"
  	ActiveRecord::Base.connection.execute clean_sql
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation, :username, :role
  validates_uniqueness_of :email, :username
  validates_presence_of :username, :email, :password, :on => :create

  ROLES = %w[admin operator viewer]
end

app/controllers/application_controller.rb
# encoding: UTF-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "Доступ запрещен."
    redirect_to login_url
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Доступ запрещен." if current_user.nil?
  end
end

app/controllers/camcorders_controller.rb
# encoding: UTF-8
class CamcordersController < ApplicationController
  load_and_authorize_resource

  def index
    @camcorders = Camcorder.all()
  end

  def show
    if params[:dt_from].blank?
      params[:dt_from] = Time.now.strftime("%d/%m/%Y 00:00:00")
    end
    if params[:dt_to].blank?
      params[:dt_to] = Time.now.strftime("%d/%m/%Y %H:%M:%S")
    end
    @records = @camcorder.Records.where("event_timestamp >= '#{params[:dt_from]}' AND event_timestamp <= '#{params[:dt_to]}'").order("event_timestamp ASC").page(params[:page])
  end

  def new
  end

  def edit
  end

  def create
    if @camcorder.save
      redirect_to camcorders_path, notice: "Новая камера была добавлена."
    else
      render "new"
    end
  end

  def update
    if @camcorder.update_attributes(params[:camcorder])
      redirect_to camcorders_path, notice: "Данные камеры были изменены."
    else
      render action: "edit"
    end
  end

  def destroy
    @camcorder.destroy
    redirect_to camcorders_path, notice: "Камера была удалена."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_authorize_resource
	
  def index
  end

  def live
  	@camcorders = Camcorder.all()
  end

  def view
  	@camcorder = Camcorder.find(params[:camcorder])
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	load_and_authorize_resource

  def index

  end

  def show
  	
  end
end

app/controllers/sessions_controller.rb
# encoding: UTF-8
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:username])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Вход успешно выполнен."
  	else
  		flash.now.alert = "Неверное имя пользователя или пароль."
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Вы вышли из системы."
  end
end

app/controllers/users_controller.rb
# encoding: UTF-8
class UsersController < ApplicationController
	load_and_authorize_resource

	def index
		@users = User.find(:all, :order => "username ASC")
	end

	def show
	end

	def new
	end

	def edit
	end

	def create
		if @user.save
			redirect_to users_path, notice: "Новый пользователь был добавлен."
		else
			render "new"
		end
	end

	def update
		if @user.update_attributes(params[:user])
			redirect_to @user, notice: "Данные пользователя были изменены."
		else
			render action: "edit"
		end
	end

	def destroy
   	@user.destroy
   	redirect_to users_url, notice: "Пользователь был удален."
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camcorders_helper.rb
module CamcordersHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/views/camcorders/_form.html.erb
<%= simple_form_for(@camcorder, :html => {:class => 'form-horizontal' }) do |f| %>
  <fieldset>
    <div class="form-inputs">
      <%= f.input :thread %>
      <%= f.input :name %>
      <%= f.input :stream_port %>
      <%= f.input :description, as: :text, :input_html => { :cols => 50, :rows => 3 } %><br />
    </div>

    <div class="form-actions">
      <%= f.submit "Сохранить", :class => "btn btn-primary" %>
      <%= link_to "Отменить", camcorders_path, :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/camcorders/create.html.erb
<h1>Camcorders#create</h1>
<p>Find me in app/views/camcorders/create.html.erb</p>

app/views/camcorders/destroy.html.erb
<h1>Camcorders#destroy</h1>
<p>Find me in app/views/camcorders/destroy.html.erb</p>

app/views/camcorders/edit.html.erb
<div>
  <h1><%= image_tag('camera24.png') %> Изменение данных о камере &quot;<%= @camcorder.name %>&quot;</h1>
</div>
<%= render :partial => 'form' %>

app/views/camcorders/index.html.erb
<%- model_class = Camcorder.new.class -%>
<div class="page-header">
  <h1><%= image_tag('camera128.png') %> Список камер</h1>
</div>
<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:thread) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @camcorders.each do |cam| %>
      <tr>
        <td><%= link_to cam.id, cam %></td>
        <td><%= link_to cam.thread, cam %></td>
        <td><%= link_to cam.name, cam %></td>
        <td><%= cam.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_camcorder_path(cam), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      camcorder_path(cam),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to t('Добавить камеру'),
            new_camcorder_path,
            :class => 'btn btn-primary' %>

app/views/camcorders/new.html.erb
<div>
  <h1><%= image_tag('camera128.png') %> Добавление камеры</h1>
</div>
<%= render :partial => 'form' %>

app/views/camcorders/show.html.erb
<div>
  <h1><%= image_tag('camera24.png') %> Записи с камеры &quot;<%= @camcorder.name %>&quot;</h1>
</div>

<form class="form-search">
	<div class="well">
	  <div id="dtpickerFrom" class="input-append date">
	    <label>Показать записи с</label>
	    <input data-format="dd/MM/yyyy hh:mm:ss" type="text" name="dt_from" value="<%= params[:dt_from] %>"></input>
	    <span class="add-on">
	      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
	      </i>
	    </span>
	  </div>
	  <div id="dtpickerTo" class="input-append date">
	    <label>по</label>
	    <input data-format="dd/MM/yyyy hh:mm:ss" type="text" name="dt_to" value="<%= params[:dt_to] %>"></input>
	    <span class="add-on">
	      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
	      </i>
	    </span>
	  </div>
	  <button type="submit" class="btn btn-primary">Показать</button>
	</div>
	<script type="text/javascript">
	  $(function() {
	    $('#dtpickerFrom').datetimepicker({
	      language: 'ru'
	    });
	  });
	  $(function() {
	    $('#dtpickerTo').datetimepicker({
	      language: 'ru'
	    });
	  });
	</script>

<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>Дата и время</th>
      <th>Просмотр</th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |rec| %>
      <tr>
        <td>
        	<%= rec.event_timestamp.to_formatted_s(:db) %> 
        </td>
        <td>
        	<%= video_tag rec.filename, :size => "320x240", :controls => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @records, renderer: BootstrapPagination::Rails, class: 'pager' %>

</form>

app/views/camcorders/update.html.erb
<h1>Camcorders#update</h1>
<p>Find me in app/views/camcorders/update.html.erb</p>

app/views/home/index.html.erb
<h1>Видеонаблюдение</h1>
<p>Вам доступен живой просмотр с камер, либо войдите в систему для расширения своих полномочий.</p>

app/views/home/live.html.erb
<table class="table table-bordered table-condensed table-hover">
	<% cnt = 0 %>
	<% @camcorders.each do |cam| %>
		<% if cnt % 3 == 0 || cnt == 0 %>
			<tr>
		<% end %>
    	<td>
        <%= link_to home_view_path(:camcorder => cam.id) do %>
    		  <img src="<%= Settings.motion_server %>:<%= cam.stream_port %>" width="320" height="240">
        <% end %>
    	</td>
    <% cnt += 1 %>
    <% if cnt % 3 == 0 %>
			</tr>
		<% end %>
  <% end %>
  <% if cnt % 3 != 0 %>
  	</tr>
  <% end %>
</table>

app/views/home/view.html.erb
<h3>Просмотр с камеры &quot;<%= @camcorder.name %>&quot;</h3>
<div>
	<img src="<%= Settings.motion_server %>:<%= @camcorder.stream_port %>">
</div>

<div class="form-actions">
  <%= link_to "Назад к живому просмотру", home_live_path, :class => "btn" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CCTV[Motion]</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_path %>">CCTV [Motion]</a>
        <div class="nav-collapse">
          <ul class="nav">
						<!-- Operator menu -->
						<% if current_user && current_user.role.in?(%w[admin operator]) %>
            	<li>
                <%= link_to camcorders_path do %>
                  <%= image_tag('camera24.png') %> Камеры
                <% end %>
              </li>
							
						<% end %>
						<!-- Admin menu -->
	          <% if current_user && current_user.role == 'admin' %>
	                  <li>
                      <%= link_to users_path do %>
                        <%= image_tag('users24.png') %> Пользователи
                      <% end %>
                    </li>
	          <% end %>
          </ul>
					<% if current_user %>
	          <p class="navbar-text pull-right">Вы вошли как <%= current_user.username %>.
							<%= link_to logout_path, :class => "btn btn-danger btn-mini" do %>
								<i class="icon-off icon-white"></i> Выход
							<% end %>
						</p>
	        <% else %>
	          <p class="navbar-text pull-right">Для начала работы необходимо выполнить вход.
	          	<%= link_to login_path, :class => "btn btn-mini btn-danger" do %>
	          		<i class="icon-lock icon-white"></i> Войти в систему
	          	<% end %>
	          </p>
	        <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
    
    <div class="row">
			<div class="span3">
        <h2>Меню</h2>
        <ul class="list-group">
          <% if current_user && current_user.role.in?(%w[admin operator viewer]) %>
            <li class="list-group-item">
              <%= link_to camcorders_path do %>
                <%= image_tag('camera24.png') %> Камеры
              <% end %>      
            </li>
          <% end %>
          <% if current_user && current_user.role == 'admin' %>
            <li class="list-group-item">
              <%= link_to users_path do %>
                <%= image_tag('users24.png') %> Пользователи
              <% end %>
            </li>
          <% end %>
            <li class="list-group-item">
              <%= link_to home_live_path do %>
                <%= image_tag('grid24.png') %> Живой просмотр
              <% end %>
            </li>
          <% if current_user %>
            <li class="list-group-item">
              <%= link_to logout_path, :class => "btn btn-danger btn-mini" do %>
                <i class="icon-off icon-white"></i> Выход
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="span9"><%= yield %></div>
    </div>
  </div>

</body>
</html>

app/views/records/index.html.erb
<h1>Record#index</h1>
<p>Find me in app/views/record/index.html.erb</p>

app/views/users/_form.html.erb
<%= simple_form_for(@user, :html => {:class => 'form-horizontal' }) do |f| %>
  <fieldset>
    <div class="form-inputs">
      <%= f.input :username %>
      <%= f.input :email %>
      <%= f.input :password %><br />
      <%= f.input :password_confirmation %><br />
      <%= f.input :role, :collection => User::ROLES, prompt: "Укажите роль" %><br />
    </div>

    <div class="form-actions">
      <%= f.submit "Сохранить", :class => "btn btn-primary" %>
      <%= link_to "Отменить", users_path, :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<div>
  <h1>Изменение данных пользователя <%= @user.username %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User.new.class -%>
<div class="page-header">
  <h1>Пользователи</h1>
</div>
<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= link_to user.username, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to t('Добавить пользователя'),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<div>
  <h1>Создание Нового пользователя</h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h1>Профиль пользователя</h1>

<p>
  <b>Username:</b>
  <%=  @user.username %>
</p>
<p>
  <b>E-Mail:</b>
  <%= @user.email %>
</p>
<p>
  <b>Роль:</b>
  <%= @user.role %>
</p>

<br />
<%= link_to 'Изменить', edit_user_path(@user), :class => "btn btn-primary" %>
<%= link_to 'Отменить', users_path, :class => "btn" %>
<%= link_to 'Удалить', user_path(@user), :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Вы уверены?')),
                      :class => 'btn btn-danger' %>